### ISSUE TITLE
Kompileerimine ei õnnestunud Ubuntus

### ISSUE THREAD

**Issue by wanradt** [UkuNano/Electric-field-simulator#1]
Tere!

Ei leidnud Su repos kompileerimisjuhendit, proovisin lihtsalt:

`$ gcc main.c -o main.o`

Ei õnnestunud, logi: 
[compiler_log.txt](https://github.com/UkuNano/Electric-field-simulator/files/11558547/compiler_log.txt)

Raylib-ist kasutasin versiooni 4.5 kuna 4.2 kusagil ei paistnud. 

Kas oled proovinud Linuxi all kompileerida? On Sul mingeid soovitusi? Ei tunne end C-s väga koduselt, aga tahtsin uudishimust Su simulaatorit proovida. 

Kui vastamine ja lahendamine on energiamahukas, siis, loomulikult, ära näe vaeva.

Kõike hääd,

Gunnar,
uudishimulik

**Comment by UkuNano** [comment]
Tere!

Arendasin selle Windowsi all, Linuxis arendamist ma hästi ei tunne.

Kompileerisin selle Raylibi installeriga kohe kaasa tulnud Notepad++ scriptiga ja GCC-ga . See script käivitab GCC nii:

`gcc -o main.exe main.c C:\raylib\raylib\src\raylib.rc.data -s -static -Os -std=c99 -Wall -IC:\raylib\raylib\src -Iexternal -DPLATFORM_DESKTOP -mwindows -lraylib -lopengl32 -lgdi32 -lwinmm`

Osad errorid olid tingitud sellest, et olin teinud viimasel hetkel muudatusi, et see Raylib 4.5 peal kompileerida (sellepärast, et Raylib 4.2 ja TCC-ga paljud antiviirused, kaasaarvatud Windows Defender, arvasid et see programm on pahavara), aga unustasin seda Githubi lehekülge uuendada. Nüüd on need errorid parandatud ja see Githubi lehekülg uuendatud.

Enamus errorid olid aga sellepärast, et Sa polnud Raylibi librarit linkinud ( -lraylib ). See fail peaks olema libraylib.a ja asuma kohas, kus kompilaator oskab selle üles leida. Asukoha saad kompilaatorile anda nii: -L/bla/blah/mingi/kaust. Lisaks on vaja ka kompilaatorile näidata kust leida raylib.h fail: -I/bla/blah/mingi/kaust.

Loodetavasti on ka [sellest Stackoverflow lingist abi](https://stackoverflow.com/questions/74834701/how-to-compile-c-with-raylib-program-in-linux-terminal).

**Comment by wanradt** [comment]
Tänud lisainfo eest, proovin mõnel vabal hetkel veel. Jõudu kooli lõpetamisel!
